# Generated by Django 3.2 on 2021-05-25 20:37

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='example@example.com', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacsine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('vacsine_for', models.CharField(default='', max_length=100)),
                ('child_age_from', system.models.IntegerRangeField()),
                ('additional_information', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChildVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.child')),
                ('vaccine', models.ManyToManyField(to='system.Vacsine')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.parent'),
        ),
    ]
