# Generated by Django 3.2 on 2021-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacsine',
            name='vacsine_for',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
