# Generated by Django 3.2.4 on 2021-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nationalid',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nationalid',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
    ]
