# Generated by Django 3.2 on 2021-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_vacsine_vacsine_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacsine',
            name='additional_information',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
