# Generated by Django 3.2 on 2021-05-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_childvaccine_child'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacsine',
            new_name='Vaccine',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='vacsine_for',
            new_name='vaccine_for',
        ),
    ]
