# Generated by Django 3.2 on 2021-05-26 16:52

from django.db import migrations
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210526_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='child_age_to',
            field=system.models.IntegerRangeField(default=10),
        ),
    ]
