# Generated by Django 3.2 on 2021-05-26 16:54

from django.db import migrations
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_vaccine_child_age_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='child_age_to',
            field=system.models.IntegerRangeField(),
        ),
    ]
