# Generated by Django 3.2 on 2021-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_seenbyparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccine',
            name='vaccine',
            field=models.ManyToManyField(blank=True, null=True, to='system.Vaccine'),
        ),
    ]
