# Generated by Django 3.2 on 2021-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_childvaccine_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccine',
            name='vaccine',
            field=models.ManyToManyField(blank=True, to='system.Vaccine'),
        ),
    ]
