# Generated by Django 3.2 on 2021-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_childvaccine_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvaccine',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
