# Generated by Django 3.2 on 2021-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_childvaccine_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
