# Generated by Django 3.2.4 on 2021-12-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='nationalid',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='parent',
            name='nationalid',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
